project_name: lab
release:
  github:
    owner: zaquestion
    name: lab
  name_template: '{{.Tag}}'

brews:
  - description: "Interacts with GitLab repositories creating/editing merge requests, issues, milestones, snippets and CI pipelines."
    homepage: "https://github.com/zaquestion/lab"
    tap:
      owner: zaquestion
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: goreleaser@carlosbecker.com
    install: bin.install "lab"
    test: |
      system "git", "init"
      %w[haunted house].each { |f| touch testpath/f }
      system "git", "add", "haunted", "house"
      system "git", "commit", "-a", "-m", "Initial Commit"
      lab_env_config = "LAB_CORE_HOST=foo LAB_CORE_USER=bar LAB_CORE_TOKEN=baz"
      assert_match "haunted\nhouse", shell_output("#{lab_env_config} #{bin}/lab ls-files").strip

scoop:
  bucket:
    owner: zaquestion
    name: scoop-bucket
  commit_author:
    name: goreleaserbot
    email: goreleaser@carlosbecker.com
  homepage: "https://github.com/zaquestion/lab"
  description: "Interacts with GitLab repositories creating/editing merge requests, issues, milestones, snippets and CI pipelines."
  license: CC0

builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
    - arm64
  ldflags: -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}
  binary: lab

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: '{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{.Arm }}{{ end }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'

changelog:
  filters:
    exclude:
      - '^\(docs\)'
      - '^\(gitlab-ci\)'
      - '^\(travis\)'
      - '^\(coverage\)'
      - '^\(tests?'
      - '^Merge pull request'
